document.addEventListener('DOMContentLoaded', function() {
    var macros = {
        '\\bbA': '\\mathbb{A}',
        '\\bbB': '\\mathbb{B}',
        '\\bbC': '\\mathbb{C}',
        '\\bbD': '\\mathbb{D}',
        '\\bbE': '\\mathbb{E}',
        '\\bbF': '\\mathbb{F}',
        '\\bbG': '\\mathbb{G}',
        '\\bbH': '\\mathbb{H}',
        '\\bbI': '\\mathbb{I}',
        '\\bbJ': '\\mathbb{J}',
        '\\bbK': '\\mathbb{K}',
        '\\bbL': '\\mathbb{L}',
        '\\bbM': '\\mathbb{M}',
        '\\bbN': '\\mathbb{N}',
        '\\bbO': '\\mathbb{O}',
        '\\bbP': '\\mathbb{P}',
        '\\bbQ': '\\mathbb{Q}',
        '\\bbR': '\\mathbb{R}',
        '\\bbS': '\\mathbb{S}',
        '\\bbT': '\\mathbb{T}',
        '\\bbU': '\\mathbb{U}',
        '\\bbV': '\\mathbb{V}',
        '\\bbW': '\\mathbb{W}',
        '\\bbX': '\\mathbb{X}',
        '\\bbY': '\\mathbb{Y}',
        '\\bbZ': '\\mathbb{Z}',

        '\\scrA': '\\mathscr{A}',
        '\\scrB': '\\mathscr{B}',
        '\\scrC': '\\mathscr{C}',
        '\\scrD': '\\mathscr{D}',
        '\\scrE': '\\mathscr{E}',
        '\\scrF': '\\mathscr{F}',
        '\\scrG': '\\mathscr{G}',
        '\\scrH': '\\mathscr{H}',
        '\\scrI': '\\mathscr{I}',
        '\\scrJ': '\\mathscr{J}',
        '\\scrK': '\\mathscr{K}',
        '\\scrL': '\\mathscr{L}',
        '\\scrM': '\\mathscr{M}',
        '\\scrN': '\\mathscr{N}',
        '\\scrO': '\\mathscr{O}',
        '\\scrP': '\\mathscr{P}',
        '\\scrQ': '\\mathscr{Q}',
        '\\scrR': '\\mathscr{R}',
        '\\scrS': '\\mathscr{S}',
        '\\scrT': '\\mathscr{T}',
        '\\scrU': '\\mathscr{U}',
        '\\scrV': '\\mathscr{V}',
        '\\scrW': '\\mathscr{W}',
        '\\scrX': '\\mathscr{X}',
        '\\scrY': '\\mathscr{Y}',
        '\\scrZ': '\\mathscr{Z}',

        '\\calA': '\\mathcal{A}',
        '\\calB': '\\mathcal{B}',
        '\\calC': '\\mathcal{C}',
        '\\calD': '\\mathcal{D}',
        '\\calE': '\\mathcal{E}',
        '\\calF': '\\mathcal{F}',
        '\\calG': '\\mathcal{G}',
        '\\calH': '\\mathcal{H}',
        '\\calI': '\\mathcal{I}',
        '\\calJ': '\\mathcal{J}',
        '\\calK': '\\mathcal{K}',
        '\\calL': '\\mathcal{L}',
        '\\calM': '\\mathcal{M}',
        '\\calN': '\\mathcal{N}',
        '\\calO': '\\mathcal{O}',
        '\\calP': '\\mathcal{P}',
        '\\calQ': '\\mathcal{Q}',
        '\\calR': '\\mathcal{R}',
        '\\calS': '\\mathcal{S}',
        '\\calT': '\\mathcal{T}',
        '\\calU': '\\mathcal{U}',
        '\\calV': '\\mathcal{V}',
        '\\calW': '\\mathcal{W}',
        '\\calX': '\\mathcal{X}',
        '\\calY': '\\mathcal{Y}',
        '\\calZ': '\\mathcal{Z}',

        '\\frakA': '\\mathfrak{A}',
        '\\frakB': '\\mathfrak{B}',
        '\\frakC': '\\mathfrak{C}',
        '\\frakD': '\\mathfrak{D}',
        '\\frakE': '\\mathfrak{E}',
        '\\frakF': '\\mathfrak{F}',
        '\\frakG': '\\mathfrak{G}',
        '\\frakH': '\\mathfrak{H}',
        '\\frakI': '\\mathfrak{I}',
        '\\frakJ': '\\mathfrak{J}',
        '\\frakK': '\\mathfrak{K}',
        '\\frakL': '\\mathfrak{L}',
        '\\frakM': '\\mathfrak{M}',
        '\\frakN': '\\mathfrak{N}',
        '\\frakO': '\\mathfrak{O}',
        '\\frakP': '\\mathfrak{P}',
        '\\frakQ': '\\mathfrak{Q}',
        '\\frakR': '\\mathfrak{R}',
        '\\frakS': '\\mathfrak{S}',
        '\\frakT': '\\mathfrak{T}',
        '\\frakU': '\\mathfrak{U}',
        '\\frakV': '\\mathfrak{V}',
        '\\frakW': '\\mathfrak{W}',
        '\\frakX': '\\mathfrak{X}',
        '\\frakY': '\\mathfrak{Y}',
        '\\frakZ': '\\mathfrak{Z}',

        '\\set': '\\{#1\\}',
        '\\inter': '#1^\\circ',
        '\\cl': '\\overline{#1}',
        '\\bound': '\\partial #1'
    };

    var mathBlocks = document.querySelectorAll('.math');
    for (var i = 0; i < mathBlocks.length; i++) {
        katex.render(mathBlocks[i].innerText, mathBlocks[i], {
            macros: macros
        });
    }
});

function go_home() {
    window.location = '/index.html';
}
